[package]
name = "stash"
version = "1.0.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.2"
linux-keyutils = "0.2.3"
serde = "1.0.164"
serde_derive = "1.0.164"
serde_json = "1.0.96"
sled = "0.34.7"
zeroize = "1.6.0"

[dev-dependencies]
tempfile = "3.2"
